name: linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install project
        # Install project
        run: |
          make install
      - name: Run linter
        # Run Linter
        run: |
          make lint
